export const navTree = [
  { name: "Home", path: "/" },
  { name: "Customer", path: "/customer" },
  { name: "Account Management", path: "/customer/account_management" },
  { name: "Active", path: "/customer/active" },
  { name: "Billing and Payments", path: "/customer/billing-and-payments" },
  { name: "Dashboard", path: "/customer/dashboard" },
  { name: "Ledger", path: "/customer/ledger" },
  { name: "Project Tracking", path: "/customer/project-tracking" },
  { name: "Projects", path: "/customer/projects" },
  { name: "Services Management", path: "/customer/services-management" },
  { name: "Setup", path: "/customer/setup" },
  { name: "Support and Assistance", path: "/customer/support-and-assistance" },
  { name: "Usage", path: "/customer/usage" },
  { name: "Developer", path: "/developer" },
  { name: "Activity Tracking", path: "/developer/activity-tracking" },
  { name: "Automated Payments", path: "/developer/automated-payments" },
  { name: "Code Contributions", path: "/developer/code-contributions" },
  { name: "Developer Dashboard", path: "/developer/dashboard" },
  {
    name: "Integration with AI Services",
    path: "/developer/integration-with-ai-services",
  },
  { name: "Developer Ledger", path: "/developer/ledger" },
  { name: "Developer Payment", path: "/developer/payment" },
  {
    name: "Real-Time Collaboration",
    path: "/developer/real-time-collaboration",
  },
];
